table 'Dados cerrado final (acho)'
	lineageTag: 616987db-ce94-46a9-af57-8bf1e81fa5f2

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cfc87eeb-6649-4699-a9cc-0e4c20694c8a
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 5e77e4cc-3c05-40b8-8c26-bc84986bbfbf
			defaultHierarchy: LocalDateTable_3f05b9e1-c337-4551-abe7-b7c66b36a187.'Hierarquia de datas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column classification
		dataType: string
		lineageTag: c91454b7-f564-4355-a95d-4cd8171aa59e
		summarizeBy: none
		sourceColumn: classification

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Focus
		dataType: int64
		formatString: 0
		lineageTag: a9d67ea0-7b98-4661-9932-5a630dd85559
		summarizeBy: sum
		sourceColumn: Focus

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: ef19d451-3558-4c71-b5d4-9ba0718a5255
		summarizeBy: none
		sourceColumn: State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Dados cerrado final (acho)' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\gabri\AppData\Roaming\Microsoft\AddIns\Dados cerrado final (acho).xlsx"), null, true),
				    #"Dados cerrado final (acho)_Sheet" = Fonte{[Item="Dados cerrado final (acho)",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Dados cerrado final (acho)_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Date", type date}, {"classification", type text}, {"Focus", Int64.Type}, {"State", type text}})
				in
				    #"Tipo Alterado"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

